### ISSUE TITLE
I get a crash with given example code 

### ISSUE THREAD

**Issue by lokeshintuit** [taskcluster/jsonschema2go#7]
CA0080ALKOCAPS:jsonschema2go v676770$ cat test.txt |  ./jsonschema2go -o mypackagename
Unknown scheme: ''
URL: '{#'
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x95a16]

goroutine 1 [running]:
panic(0x41f4c0, 0xc82000e0d0)
        /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
github.com/taskcluster/jsonschema2go.(_Job).loadJsonSchema(0xc8200168a0, 0xc82011e6c6, 0x2, 0x0, 0x0, 0x0)
        /Users/v676770/sep_code/dakota/vendor-library/src/github.com/taskcluster/jsonschema2go/jsonschema.go:578 +0x496
github.com/taskcluster/jsonschema2go.(_Job).cacheJsonSchema(0xc8200168a0, 0xc82011e30a, 0x1, 0x0, 0x0, 0x0)
        /Users/v676770/sep_code/dakota/vendor-library/src/github.com/taskcluster/jsonschema2go/jsonschema.go:606 +0x1a2
github.com/taskcluster/jsonschema2go.(*Job).Execute(0xc8200168a0, 0xc8200168a0, 0x0, 0x0)
        /Users/v676770/sep_code/dakota/vendor-library/src/github.com/taskcluster/jsonschema2go/jsonschema.go:657 +0x347
main.main()
        /Users/v676770/sep_code/dakota/vendor-library/src/github.com/taskcluster/jsonschema2go/jsonschema2go/cli.go:77 +0x25f

**Comment by lokeshintuit** [comment]
code has default which does not work. 
it is up to you to fix this. However I am able to generate go code through HTTP. 

thanks.

**Comment by petemoore** [comment]
Sorry, @lokeshverizon I've only just seen this issue! I'll have a look...

**Comment by petemoore** [comment]
I think the issue is you are piping a schema to jsonschema2go - you should pipe a url. In other words, you should instead run:

```
$ echo file://test.txt | ./jsonschema2go -o mypackagename
```
